#!/usr/bin/perl
my $flag = shift(@ARGV);
if($flag =~ /-s/) {
    print "Clean up assemmbly after compilation.\n";
} else {
   unshift(@ARGV, $flag);
   $flag = '';
}

foreach (@ARGV) {
    
    print "./codegen $_\n";
    system("./codegen $_");
    
    $_ =~ m/([^\^\?\*\/\:\;\{\}\\]+)\.alice/;
    my $filename = $1;
    
    if(($? << 8) == 0) {

    	my @args;

        my $arch = `uname -a`;
        if($arch !~ /.*armv6.*/) {
            push(@args, "arm-elf-gcc");
        } else {
            push(@args, "gcc");
        }

        push(@args, "-o $filename $_.s");

        open my $source, '<', $_; 
        if(<$source> =~ /###include io/) {
            push(@args, "utils.o");
        }
        close $source;

    	print "@args\n\n";
        *STDERR = *STDOUT;
        system("@args");

        if($? != 0) {
            print "Failure to execute. $!\n";
        }

        if($flag) {
            print "HELLO!"; 
            system("rm $_.s");

            if($? != 0) {
                print "Failure to execute. $!\n";
            }
        } 
    }
}
