#!/usr/bin/perl
my $flag = shift(@ARGV);
if($flag =~ /-s/) {
    print "Clean up assemmbly after compilation.\n";
} else {
   unshift(@ARGV, $flag);
   $flag = '';
}
foreach (@ARGV) {
    *STDERR = *STDOUT;
    print "./compile $_\n";
    `./codegen $_`;
    $_ =~ m/([^\^\?\*\/\:\;\{\}\\]+)\.alice/;
    my $filename = $1;
    print "$filename\n";
    if(($? << 8) == 0) {
	my $arch = `uname -a`;
        if($arch =~ /.*armv6.*/) {
            open my $source, '<', $_; 
            if(<$source> =~ /###include io/) {
                print "gcc -o $filename $_.s utils.o\n\n";
                `gcc -o $filename $_.s utils.o`;
            } else {
                print "gcc -o $filename $_.s\n\n";
               `gcc -o $filename $_.s`;
            }
            close $source;
        } else {
            print "Can only compile to execuable on ARMv6!\n";
	}
        if($flag) { 
            `rm $_.s`;
        } 
    }
}
