/** \file
 *  This C source file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : E:\\Users\\Owen\\Documents\\Work\\Year2\\Laboratory\\MAlice\\malice\\Milestone 2\\MAlice.g
 *     -                            On : 2012-11-03 11:00:46
 *     -                for the parser : MAliceParserParser
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "MAliceParser.h"
/* ----------------------------------------- */





/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */

#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   pMAliceParser_##scope##_SCOPE
#define SCOPE_STACK(scope)  pMAliceParser_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->pMAliceParser_##scope##Top
#define	SCOPE_SIZE(scope)		ctx->pMAliceParser_##scope##Stack_limit
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))

/* Macros for accessing things in the parser
 */

#undef	    PARSER
#undef	    RECOGNIZER
#undef	    HAVEPARSEDRULE
#undef		MEMOIZE
#undef	    INPUT
#undef	    STRSTREAM
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    MATCHT
#undef	    MATCHANYT
#undef	    FOLLOWSTACK
#undef	    FOLLOWPUSH
#undef	    FOLLOWPOP
#undef	    PRECOVER
#undef	    PREPORTERROR
#undef	    LA
#undef	    LT
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    PERRORRECOVERY
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    RECOVERFROMMISMATCHEDSET
#undef	    RECOVERFROMMISMATCHEDELEMENT
#undef		INDEX
#undef      ADAPTOR
#undef		SEEK
#undef	    RULEMEMO
#undef		DBG

#define	    PARSER				ctx->pParser
#define	    RECOGNIZER				PARSER->rec
#define	    PSRSTATE				RECOGNIZER->state
#define	    HAVEPARSEDRULE(r)			RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define	    MEMOIZE(ri,si)			RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define	    INPUT				PARSER->tstream
#define	    STRSTREAM				INPUT
#define	    ISTREAM				INPUT->istream
#define	    INDEX()				ISTREAM->index(INPUT->istream)
#define	    HASEXCEPTION()			(PSRSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION				PSRSTATE->exception
#define	    MATCHT(t, fs)			RECOGNIZER->match(RECOGNIZER, t, fs)
#define	    MATCHANYT()				RECOGNIZER->matchAny(RECOGNIZER)
#define	    FOLLOWSTACK				PSRSTATE->following
#ifdef  SKIP_FOLLOW_SETS
#define	    FOLLOWPUSH(x)
#define	    FOLLOWPOP()
#else
#define	    FOLLOWPUSH(x)			FOLLOWSTACK->push(FOLLOWSTACK, ((void *)(&(x))), NULL)
#define	    FOLLOWPOP()				FOLLOWSTACK->pop(FOLLOWSTACK)
#endif
#define	    PRECOVER()				RECOGNIZER->recover(RECOGNIZER)
#define	    PREPORTERROR()			RECOGNIZER->reportError(RECOGNIZER)
#define	    LA(n)				INPUT->istream->_LA(ISTREAM, n)
#define	    LT(n)				INPUT->_LT(INPUT, n)
#define	    CONSTRUCTEX()			RECOGNIZER->exConstruct(RECOGNIZER)
#define	    CONSUME()				ISTREAM->consume(ISTREAM)
#define	    MARK()				ISTREAM->mark(ISTREAM)
#define	    REWIND(m)				ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()			ISTREAM->rewindLast(ISTREAM)
#define	    SEEK(n)				ISTREAM->seek(ISTREAM, n)
#define	    PERRORRECOVERY			PSRSTATE->errorRecovery
#define	    FAILEDFLAG				PSRSTATE->failed
#define	    HASFAILED()				(FAILEDFLAG == ANTLR3_TRUE)
#define	    BACKTRACKING			PSRSTATE->backtracking
#define	    RECOVERFROMMISMATCHEDSET(s)		RECOGNIZER->recoverFromMismatchedSet(RECOGNIZER, s)
#define	    RECOVERFROMMISMATCHEDELEMENT(e)	RECOGNIZER->recoverFromMismatchedElement(RECOGNIZER, s)
#define     ADAPTOR                         ctx->adaptor
#define		RULEMEMO						PSRSTATE->ruleMemo
#define		DBG								RECOGNIZER->debugger


#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */


/** \brief Table of all token names in symbolic order, mainly used for
 *         error reporting.
 */
pANTLR3_UINT8   MAliceParserTokenNames[31+4]
     = {
        (pANTLR3_UINT8) "<invalid>",       /* String to print to indicate an invalid token */
        (pANTLR3_UINT8) "<EOR>",
        (pANTLR3_UINT8) "<DOWN>",
        (pANTLR3_UINT8) "<UP>",
        (pANTLR3_UINT8) "CHAR",
        (pANTLR3_UINT8) "ID",
        (pANTLR3_UINT8) "INT",
        (pANTLR3_UINT8) "'%'",
        (pANTLR3_UINT8) "'&'",
        (pANTLR3_UINT8) "'()'",
        (pANTLR3_UINT8) "'*'",
        (pANTLR3_UINT8) "'+'",
        (pANTLR3_UINT8) "','",
        (pANTLR3_UINT8) "'.'",
        (pANTLR3_UINT8) "'/'",
        (pANTLR3_UINT8) "'Alice.'",
        (pANTLR3_UINT8) "'The'",
        (pANTLR3_UINT8) "'^'",
        (pANTLR3_UINT8) "'and'",
        (pANTLR3_UINT8) "'ate'",
        (pANTLR3_UINT8) "'became'",
        (pANTLR3_UINT8) "'but'",
        (pANTLR3_UINT8) "'closed'",
        (pANTLR3_UINT8) "'drank'",
        (pANTLR3_UINT8) "'hatta'",
        (pANTLR3_UINT8) "'letter'",
        (pANTLR3_UINT8) "'looking-glass'",
        (pANTLR3_UINT8) "'number'",
        (pANTLR3_UINT8) "'opened'",
        (pANTLR3_UINT8) "'said'",
        (pANTLR3_UINT8) "'then'",
        (pANTLR3_UINT8) "'too'",
        (pANTLR3_UINT8) "'was a'",
        (pANTLR3_UINT8) "'|'",
        (pANTLR3_UINT8) "'~'"
       };



// Forward declare the locally static matching functions we have generated.
//
static 
 void
	program    (pMAliceParser ctx);
static 
 void
	statementList    (pMAliceParser ctx);
static 
 void
	printReturn    (pMAliceParser ctx);
static 
 void
	statement    (pMAliceParser ctx);
static 
 void
	declaration    (pMAliceParser ctx);
static 
 void
	assignment    (pMAliceParser ctx);
static 
 void
	step    (pMAliceParser ctx);
static 
 void
	expression    (pMAliceParser ctx);
static 
 void
	or    (pMAliceParser ctx);
static 
 void
	and    (pMAliceParser ctx);
static 
 void
	add    (pMAliceParser ctx);
static 
 void
	ones    (pMAliceParser ctx);
static 
 void
	term    (pMAliceParser ctx);
static void	MAliceParserFree(pMAliceParser ctx);
static void     MAliceParserReset (pMAliceParser ctx);

/* For use in tree output where we are accumulating rule labels via label += ruleRef
 * we need a function that knows how to free a return scope when the list is destroyed.
 * We cannot just use ANTLR3_FREE because in debug tracking mode, this is a macro.
 */
static	void ANTLR3_CDECL freeScope(void * scope)
{
    ANTLR3_FREE(scope);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "E:\\Users\\Owen\\Documents\\Work\\Year2\\Laboratory\\MAlice\\malice\\Milestone 2\\MAlice.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}
/** \brief Create a new MAliceParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pMAliceParser
MAliceParserNew   (pANTLR3_COMMON_TOKEN_STREAM instream)
{
	// See if we can create a new parser with the standard constructor
	//
	return MAliceParserNewSSD(instream, NULL);
}

/** \brief Create a new MAliceParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pMAliceParser
MAliceParserNewSSD   (pANTLR3_COMMON_TOKEN_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    pMAliceParser ctx;	    /* Context structure we will build and return   */

    ctx	= (pMAliceParser) ANTLR3_CALLOC(1, sizeof(MAliceParser));

    if	(ctx == NULL)
    {
		// Failed to allocate memory for parser context
		//
        return  NULL;
    }

    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * the base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 parser function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function.
     *
     * We don't use the macros defined in MAliceParser.h here, in order that you can get a sense
     * of what goes where.
     */

    /* Create a base parser/recognizer, using the supplied token stream
     */
    ctx->pParser	    = antlr3ParserNewStream(ANTLR3_SIZE_HINT, instream->tstream, state);
    /* Install the implementation of our MAliceParser interface
     */
    ctx->program	= program;
    ctx->statementList	= statementList;
    ctx->printReturn	= printReturn;
    ctx->statement	= statement;
    ctx->declaration	= declaration;
    ctx->assignment	= assignment;
    ctx->step	= step;
    ctx->expression	= expression;
    ctx->or	= or;
    ctx->and	= and;
    ctx->add	= add;
    ctx->ones	= ones;
    ctx->term	= term;
    ctx->free			= MAliceParserFree;
    ctx->reset			= MAliceParserReset;
    ctx->getGrammarFileName	= getGrammarFileName;

    /* Install the scope pushing methods.
     */

    /* Install the token table
     */
    PSRSTATE->tokenNames   = MAliceParserTokenNames;


    /* Return the newly built parser to the caller
     */
    return  ctx;
}

static void
MAliceParserReset (pMAliceParser ctx)
{
    RECOGNIZER->reset(RECOGNIZER);
}

/** Free the parser resources
 */
 static void
 MAliceParserFree(pMAliceParser ctx)
 {
    /* Free any scope memory
     */

	// Free this parser
	//
    ctx->pParser->free(ctx->pParser);


    ANTLR3_FREE(ctx);

    /* Everything is released, so we can return
     */
    return;
 }

/** Return token names used by this 
parser

 *
 * The returned pointer is used as an index into the token names table (using the token
 * number as the index).
 *
 * \return Pointer to first char * in the table.
 */
static pANTLR3_UINT8    *getTokenNames()
{
        return MAliceParserTokenNames;
}


/* Declare the bitsets
 */
/** Bitset defining follow set for error recovery in rule state: FOLLOW_16_in_program22  */
static	ANTLR3_BITWORD FOLLOW_16_in_program22_bits[]	= { ANTLR3_UINT64_LIT(0x0000000004000000) };
static  ANTLR3_BITSET_LIST FOLLOW_16_in_program22	= { FOLLOW_16_in_program22_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_26_in_program24  */
static	ANTLR3_BITWORD FOLLOW_26_in_program24_bits[]	= { ANTLR3_UINT64_LIT(0x0000000001000000) };
static  ANTLR3_BITSET_LIST FOLLOW_26_in_program24	= { FOLLOW_26_in_program24_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_24_in_program26  */
static	ANTLR3_BITWORD FOLLOW_24_in_program26_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000200) };
static  ANTLR3_BITSET_LIST FOLLOW_24_in_program26	= { FOLLOW_24_in_program26_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_9_in_program28  */
static	ANTLR3_BITWORD FOLLOW_9_in_program28_bits[]	= { ANTLR3_UINT64_LIT(0x0000000010000000) };
static  ANTLR3_BITSET_LIST FOLLOW_9_in_program28	= { FOLLOW_9_in_program28_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_28_in_program30  */
static	ANTLR3_BITWORD FOLLOW_28_in_program30_bits[]	= { ANTLR3_UINT64_LIT(0x0000000400000060) };
static  ANTLR3_BITSET_LIST FOLLOW_28_in_program30	= { FOLLOW_28_in_program30_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_statementList_in_program32  */
static	ANTLR3_BITWORD FOLLOW_statementList_in_program32_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000400000) };
static  ANTLR3_BITSET_LIST FOLLOW_statementList_in_program32	= { FOLLOW_statementList_in_program32_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_22_in_program34  */
static	ANTLR3_BITWORD FOLLOW_22_in_program34_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000000) };
static  ANTLR3_BITSET_LIST FOLLOW_22_in_program34	= { FOLLOW_22_in_program34_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_EOF_in_program36  */
static	ANTLR3_BITWORD FOLLOW_EOF_in_program36_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_EOF_in_program36	= { FOLLOW_EOF_in_program36_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_statement_in_statementList43  */
static	ANTLR3_BITWORD FOLLOW_statement_in_statementList43_bits[]	= { ANTLR3_UINT64_LIT(0x0000000040243000) };
static  ANTLR3_BITSET_LIST FOLLOW_statement_in_statementList43	= { FOLLOW_statement_in_statementList43_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_set_in_statementList45  */
static	ANTLR3_BITWORD FOLLOW_set_in_statementList45_bits[]	= { ANTLR3_UINT64_LIT(0x0000000400000060) };
static  ANTLR3_BITSET_LIST FOLLOW_set_in_statementList45	= { FOLLOW_set_in_statementList45_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_statementList_in_statementList65  */
static	ANTLR3_BITWORD FOLLOW_statementList_in_statementList65_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_statementList_in_statementList65	= { FOLLOW_statementList_in_statementList65_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_printReturn_in_statementList69  */
static	ANTLR3_BITWORD FOLLOW_printReturn_in_statementList69_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_printReturn_in_statementList69	= { FOLLOW_printReturn_in_statementList69_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expression_in_printReturn77  */
static	ANTLR3_BITWORD FOLLOW_expression_in_printReturn77_bits[]	= { ANTLR3_UINT64_LIT(0x0000000020000000) };
static  ANTLR3_BITSET_LIST FOLLOW_expression_in_printReturn77	= { FOLLOW_expression_in_printReturn77_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_29_in_printReturn79  */
static	ANTLR3_BITWORD FOLLOW_29_in_printReturn79_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000008000) };
static  ANTLR3_BITSET_LIST FOLLOW_29_in_printReturn79	= { FOLLOW_29_in_printReturn79_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_15_in_printReturn81  */
static	ANTLR3_BITWORD FOLLOW_15_in_printReturn81_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_15_in_printReturn81	= { FOLLOW_15_in_printReturn81_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_declaration_in_statement88  */
static	ANTLR3_BITWORD FOLLOW_declaration_in_statement88_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_declaration_in_statement88	= { FOLLOW_declaration_in_statement88_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_assignment_in_statement92  */
static	ANTLR3_BITWORD FOLLOW_assignment_in_statement92_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_assignment_in_statement92	= { FOLLOW_assignment_in_statement92_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_step_in_statement96  */
static	ANTLR3_BITWORD FOLLOW_step_in_statement96_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_step_in_statement96	= { FOLLOW_step_in_statement96_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ID_in_declaration104  */
static	ANTLR3_BITWORD FOLLOW_ID_in_declaration104_bits[]	= { ANTLR3_UINT64_LIT(0x0000000100000000) };
static  ANTLR3_BITSET_LIST FOLLOW_ID_in_declaration104	= { FOLLOW_ID_in_declaration104_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_32_in_declaration106  */
static	ANTLR3_BITWORD FOLLOW_32_in_declaration106_bits[]	= { ANTLR3_UINT64_LIT(0x000000000A000000) };
static  ANTLR3_BITSET_LIST FOLLOW_32_in_declaration106	= { FOLLOW_32_in_declaration106_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_set_in_declaration108  */
static	ANTLR3_BITWORD FOLLOW_set_in_declaration108_bits[]	= { ANTLR3_UINT64_LIT(0x0000000080000002) };
static  ANTLR3_BITSET_LIST FOLLOW_set_in_declaration108	= { FOLLOW_set_in_declaration108_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_31_in_declaration118  */
static	ANTLR3_BITWORD FOLLOW_31_in_declaration118_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_31_in_declaration118	= { FOLLOW_31_in_declaration118_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ID_in_assignment127  */
static	ANTLR3_BITWORD FOLLOW_ID_in_assignment127_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000100000) };
static  ANTLR3_BITSET_LIST FOLLOW_ID_in_assignment127	= { FOLLOW_ID_in_assignment127_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_20_in_assignment129  */
static	ANTLR3_BITWORD FOLLOW_20_in_assignment129_bits[]	= { ANTLR3_UINT64_LIT(0x0000000400000060) };
static  ANTLR3_BITSET_LIST FOLLOW_20_in_assignment129	= { FOLLOW_20_in_assignment129_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expression_in_assignment131  */
static	ANTLR3_BITWORD FOLLOW_expression_in_assignment131_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_expression_in_assignment131	= { FOLLOW_expression_in_assignment131_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ID_in_assignment135  */
static	ANTLR3_BITWORD FOLLOW_ID_in_assignment135_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000100000) };
static  ANTLR3_BITSET_LIST FOLLOW_ID_in_assignment135	= { FOLLOW_ID_in_assignment135_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_20_in_assignment137  */
static	ANTLR3_BITWORD FOLLOW_20_in_assignment137_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000010) };
static  ANTLR3_BITSET_LIST FOLLOW_20_in_assignment137	= { FOLLOW_20_in_assignment137_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_CHAR_in_assignment139  */
static	ANTLR3_BITWORD FOLLOW_CHAR_in_assignment139_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_CHAR_in_assignment139	= { FOLLOW_CHAR_in_assignment139_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ID_in_step147  */
static	ANTLR3_BITWORD FOLLOW_ID_in_step147_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000880000) };
static  ANTLR3_BITSET_LIST FOLLOW_ID_in_step147	= { FOLLOW_ID_in_step147_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_set_in_step149  */
static	ANTLR3_BITWORD FOLLOW_set_in_step149_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_set_in_step149	= { FOLLOW_set_in_step149_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_or_in_expression162  */
static	ANTLR3_BITWORD FOLLOW_or_in_expression162_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000020002) };
static  ANTLR3_BITSET_LIST FOLLOW_or_in_expression162	= { FOLLOW_or_in_expression162_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_17_in_expression165  */
static	ANTLR3_BITWORD FOLLOW_17_in_expression165_bits[]	= { ANTLR3_UINT64_LIT(0x0000000400000060) };
static  ANTLR3_BITSET_LIST FOLLOW_17_in_expression165	= { FOLLOW_17_in_expression165_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_or_in_expression167  */
static	ANTLR3_BITWORD FOLLOW_or_in_expression167_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000020002) };
static  ANTLR3_BITSET_LIST FOLLOW_or_in_expression167	= { FOLLOW_or_in_expression167_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_and_in_or177  */
static	ANTLR3_BITWORD FOLLOW_and_in_or177_bits[]	= { ANTLR3_UINT64_LIT(0x0000000200000002) };
static  ANTLR3_BITSET_LIST FOLLOW_and_in_or177	= { FOLLOW_and_in_or177_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_33_in_or180  */
static	ANTLR3_BITWORD FOLLOW_33_in_or180_bits[]	= { ANTLR3_UINT64_LIT(0x0000000400000060) };
static  ANTLR3_BITSET_LIST FOLLOW_33_in_or180	= { FOLLOW_33_in_or180_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_and_in_or182  */
static	ANTLR3_BITWORD FOLLOW_and_in_or182_bits[]	= { ANTLR3_UINT64_LIT(0x0000000200000002) };
static  ANTLR3_BITSET_LIST FOLLOW_and_in_or182	= { FOLLOW_and_in_or182_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_add_in_and193  */
static	ANTLR3_BITWORD FOLLOW_add_in_and193_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000102) };
static  ANTLR3_BITSET_LIST FOLLOW_add_in_and193	= { FOLLOW_add_in_and193_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_8_in_and196  */
static	ANTLR3_BITWORD FOLLOW_8_in_and196_bits[]	= { ANTLR3_UINT64_LIT(0x0000000400000060) };
static  ANTLR3_BITSET_LIST FOLLOW_8_in_and196	= { FOLLOW_8_in_and196_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_add_in_and198  */
static	ANTLR3_BITWORD FOLLOW_add_in_and198_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000102) };
static  ANTLR3_BITSET_LIST FOLLOW_add_in_and198	= { FOLLOW_add_in_and198_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ones_in_add208  */
static	ANTLR3_BITWORD FOLLOW_ones_in_add208_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000802) };
static  ANTLR3_BITSET_LIST FOLLOW_ones_in_add208	= { FOLLOW_ones_in_add208_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_11_in_add211  */
static	ANTLR3_BITWORD FOLLOW_11_in_add211_bits[]	= { ANTLR3_UINT64_LIT(0x0000000400000060) };
static  ANTLR3_BITSET_LIST FOLLOW_11_in_add211	= { FOLLOW_11_in_add211_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ones_in_add213  */
static	ANTLR3_BITWORD FOLLOW_ones_in_add213_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000802) };
static  ANTLR3_BITSET_LIST FOLLOW_ones_in_add213	= { FOLLOW_ones_in_add213_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_term_in_ones223  */
static	ANTLR3_BITWORD FOLLOW_term_in_ones223_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000004482) };
static  ANTLR3_BITSET_LIST FOLLOW_term_in_ones223	= { FOLLOW_term_in_ones223_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_set_in_ones226  */
static	ANTLR3_BITWORD FOLLOW_set_in_ones226_bits[]	= { ANTLR3_UINT64_LIT(0x0000000400000060) };
static  ANTLR3_BITSET_LIST FOLLOW_set_in_ones226	= { FOLLOW_set_in_ones226_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_term_in_ones238  */
static	ANTLR3_BITWORD FOLLOW_term_in_ones238_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000004482) };
static  ANTLR3_BITSET_LIST FOLLOW_term_in_ones238	= { FOLLOW_term_in_ones238_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_34_in_term249  */
static	ANTLR3_BITWORD FOLLOW_34_in_term249_bits[]	= { ANTLR3_UINT64_LIT(0x0000000400000060) };
static  ANTLR3_BITSET_LIST FOLLOW_34_in_term249	= { FOLLOW_34_in_term249_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_term_in_term251  */
static	ANTLR3_BITWORD FOLLOW_term_in_term251_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_term_in_term251	= { FOLLOW_term_in_term251_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ID_in_term256  */
static	ANTLR3_BITWORD FOLLOW_ID_in_term256_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_ID_in_term256	= { FOLLOW_ID_in_term256_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_INT_in_term260  */
static	ANTLR3_BITWORD FOLLOW_INT_in_term260_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_INT_in_term260	= { FOLLOW_INT_in_term260_bits, 1	};


/* ==============================================
 * Parsing rules
 */
/**
 * $ANTLR start program
 * E:\\Users\\Owen\\Documents\\Work\\Year2\\Laboratory\\MAlice\\malice\\Milestone 2\\MAlice.g:8:1: program : 'The' 'looking-glass' 'hatta' '()' 'opened' statementList 'closed' EOF ;
 */
static void
program(pMAliceParser ctx)
{
    /* Initialize rule variables
     */

    {
        // E:\\Users\\Owen\\Documents\\Work\\Year2\\Laboratory\\MAlice\\malice\\Milestone 2\\MAlice.g:8:8: ( 'The' 'looking-glass' 'hatta' '()' 'opened' statementList 'closed' EOF )
        // E:\\Users\\Owen\\Documents\\Work\\Year2\\Laboratory\\MAlice\\malice\\Milestone 2\\MAlice.g:8:10: 'The' 'looking-glass' 'hatta' '()' 'opened' statementList 'closed' EOF
        {
             MATCHT(16, &FOLLOW_16_in_program22);
            if  (HASEXCEPTION())
            {
                goto ruleprogramEx;
            }


             MATCHT(26, &FOLLOW_26_in_program24);
            if  (HASEXCEPTION())
            {
                goto ruleprogramEx;
            }


             MATCHT(24, &FOLLOW_24_in_program26);
            if  (HASEXCEPTION())
            {
                goto ruleprogramEx;
            }


             MATCHT(9, &FOLLOW_9_in_program28);
            if  (HASEXCEPTION())
            {
                goto ruleprogramEx;
            }


             MATCHT(28, &FOLLOW_28_in_program30);
            if  (HASEXCEPTION())
            {
                goto ruleprogramEx;
            }


            FOLLOWPUSH(FOLLOW_statementList_in_program32);
            statementList(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleprogramEx;
            }


             MATCHT(22, &FOLLOW_22_in_program34);
            if  (HASEXCEPTION())
            {
                goto ruleprogramEx;
            }


             MATCHT(EOF, &FOLLOW_EOF_in_program36);
            if  (HASEXCEPTION())
            {
                goto ruleprogramEx;
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleprogramEx; /* Prevent compiler warnings */
    ruleprogramEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end program */

/**
 * $ANTLR start statementList
 * E:\\Users\\Owen\\Documents\\Work\\Year2\\Laboratory\\MAlice\\malice\\Milestone 2\\MAlice.g:10:1: statementList : ( statement ( 'and' | 'but' | 'then' | ',' | '.' ) statementList | printReturn );
 */
static void
statementList(pMAliceParser ctx)
{
    /* Initialize rule variables
     */

    {
        {
            //  E:\\Users\\Owen\\Documents\\Work\\Year2\\Laboratory\\MAlice\\malice\\Milestone 2\\MAlice.g:10:14: ( statement ( 'and' | 'but' | 'then' | ',' | '.' ) statementList | printReturn )

            ANTLR3_UINT32 alt1;

            alt1=2;

            switch ( LA(1) )
            {
            case ID:
            	{
            		switch ( LA(2) )
            		{
            		case 19:
            		case 20:
            		case 23:
            		case 32:
            			{
            				alt1=1;
            			}
            		    break;
            		case 7:
            		case 8:
            		case 10:
            		case 11:
            		case 14:
            		case 17:
            		case 29:
            		case 33:
            			{
            				alt1=2;
            			}
            		    break;

            		default:
            		    CONSTRUCTEX();
            		    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            		    EXCEPTION->message      = (void *)"";
            		    EXCEPTION->decisionNum  = 1;
            		    EXCEPTION->state        = 1;


            		    goto rulestatementListEx;

            		}

            	}
                break;
            case INT:
            case 34:
            	{
            		alt1=2;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 1;
                EXCEPTION->state        = 0;


                goto rulestatementListEx;

            }

            switch (alt1)
            {
        	case 1:
        	    // E:\\Users\\Owen\\Documents\\Work\\Year2\\Laboratory\\MAlice\\malice\\Milestone 2\\MAlice.g:10:16: statement ( 'and' | 'but' | 'then' | ',' | '.' ) statementList
        	    {
        	        FOLLOWPUSH(FOLLOW_statement_in_statementList43);
        	        statement(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestatementListEx;
        	        }


        	        if ( ((LA(1) >= 12) && (LA(1) <= 13)) || LA(1) == 18 || LA(1) == 21 || LA(1) == 30 )
        	        {
        	            CONSUME();
        	            PERRORRECOVERY=ANTLR3_FALSE;
        	        }
        	        else
        	        {
        	            CONSTRUCTEX();
        	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;
        	            EXCEPTION->expectingSet = NULL;

        	            goto rulestatementListEx;
        	        }


        	        FOLLOWPUSH(FOLLOW_statementList_in_statementList65);
        	        statementList(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestatementListEx;
        	        }


        	    }
        	    break;
        	case 2:
        	    // E:\\Users\\Owen\\Documents\\Work\\Year2\\Laboratory\\MAlice\\malice\\Milestone 2\\MAlice.g:10:79: printReturn
        	    {
        	        FOLLOWPUSH(FOLLOW_printReturn_in_statementList69);
        	        printReturn(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestatementListEx;
        	        }


        	    }
        	    break;

            }
        }
    }

    // This is where rules clean up and exit
    //
    goto rulestatementListEx; /* Prevent compiler warnings */
    rulestatementListEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end statementList */

/**
 * $ANTLR start printReturn
 * E:\\Users\\Owen\\Documents\\Work\\Year2\\Laboratory\\MAlice\\malice\\Milestone 2\\MAlice.g:12:1: printReturn : expression 'said' 'Alice.' ;
 */
static void
printReturn(pMAliceParser ctx)
{
    /* Initialize rule variables
     */

    {
        // E:\\Users\\Owen\\Documents\\Work\\Year2\\Laboratory\\MAlice\\malice\\Milestone 2\\MAlice.g:12:12: ( expression 'said' 'Alice.' )
        // E:\\Users\\Owen\\Documents\\Work\\Year2\\Laboratory\\MAlice\\malice\\Milestone 2\\MAlice.g:12:14: expression 'said' 'Alice.'
        {
            FOLLOWPUSH(FOLLOW_expression_in_printReturn77);
            expression(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleprintReturnEx;
            }


             MATCHT(29, &FOLLOW_29_in_printReturn79);
            if  (HASEXCEPTION())
            {
                goto ruleprintReturnEx;
            }


             MATCHT(15, &FOLLOW_15_in_printReturn81);
            if  (HASEXCEPTION())
            {
                goto ruleprintReturnEx;
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleprintReturnEx; /* Prevent compiler warnings */
    ruleprintReturnEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end printReturn */

/**
 * $ANTLR start statement
 * E:\\Users\\Owen\\Documents\\Work\\Year2\\Laboratory\\MAlice\\malice\\Milestone 2\\MAlice.g:14:1: statement : ( declaration | assignment | step );
 */
static void
statement(pMAliceParser ctx)
{
    /* Initialize rule variables
     */

    {
        {
            //  E:\\Users\\Owen\\Documents\\Work\\Year2\\Laboratory\\MAlice\\malice\\Milestone 2\\MAlice.g:14:10: ( declaration | assignment | step )

            ANTLR3_UINT32 alt2;

            alt2=3;

            switch ( LA(1) )
            {
            case ID:
            	{
            		switch ( LA(2) )
            		{
            		case 32:
            			{
            				alt2=1;
            			}
            		    break;
            		case 20:
            			{
            				alt2=2;
            			}
            		    break;
            		case 19:
            		case 23:
            			{
            				alt2=3;
            			}
            		    break;

            		default:
            		    CONSTRUCTEX();
            		    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            		    EXCEPTION->message      = (void *)"";
            		    EXCEPTION->decisionNum  = 2;
            		    EXCEPTION->state        = 1;


            		    goto rulestatementEx;

            		}

            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 2;
                EXCEPTION->state        = 0;


                goto rulestatementEx;

            }

            switch (alt2)
            {
        	case 1:
        	    // E:\\Users\\Owen\\Documents\\Work\\Year2\\Laboratory\\MAlice\\malice\\Milestone 2\\MAlice.g:14:12: declaration
        	    {
        	        FOLLOWPUSH(FOLLOW_declaration_in_statement88);
        	        declaration(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestatementEx;
        	        }


        	    }
        	    break;
        	case 2:
        	    // E:\\Users\\Owen\\Documents\\Work\\Year2\\Laboratory\\MAlice\\malice\\Milestone 2\\MAlice.g:14:26: assignment
        	    {
        	        FOLLOWPUSH(FOLLOW_assignment_in_statement92);
        	        assignment(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestatementEx;
        	        }


        	    }
        	    break;
        	case 3:
        	    // E:\\Users\\Owen\\Documents\\Work\\Year2\\Laboratory\\MAlice\\malice\\Milestone 2\\MAlice.g:14:39: step
        	    {
        	        FOLLOWPUSH(FOLLOW_step_in_statement96);
        	        step(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestatementEx;
        	        }


        	    }
        	    break;

            }
        }
    }

    // This is where rules clean up and exit
    //
    goto rulestatementEx; /* Prevent compiler warnings */
    rulestatementEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end statement */

/**
 * $ANTLR start declaration
 * E:\\Users\\Owen\\Documents\\Work\\Year2\\Laboratory\\MAlice\\malice\\Milestone 2\\MAlice.g:16:1: declaration : ( ID 'was a' ( 'number' | 'letter' ) ) ( ( 'too' )? ) ;
 */
static void
declaration(pMAliceParser ctx)
{
    /* Initialize rule variables
     */

    {
        // E:\\Users\\Owen\\Documents\\Work\\Year2\\Laboratory\\MAlice\\malice\\Milestone 2\\MAlice.g:16:12: ( ( ID 'was a' ( 'number' | 'letter' ) ) ( ( 'too' )? ) )
        // E:\\Users\\Owen\\Documents\\Work\\Year2\\Laboratory\\MAlice\\malice\\Milestone 2\\MAlice.g:16:14: ( ID 'was a' ( 'number' | 'letter' ) ) ( ( 'too' )? )
        {
            // E:\\Users\\Owen\\Documents\\Work\\Year2\\Laboratory\\MAlice\\malice\\Milestone 2\\MAlice.g:16:14: ( ID 'was a' ( 'number' | 'letter' ) )
            // E:\\Users\\Owen\\Documents\\Work\\Year2\\Laboratory\\MAlice\\malice\\Milestone 2\\MAlice.g:16:15: ID 'was a' ( 'number' | 'letter' )
            {
                 MATCHT(ID, &FOLLOW_ID_in_declaration104);
                if  (HASEXCEPTION())
                {
                    goto ruledeclarationEx;
                }


                 MATCHT(32, &FOLLOW_32_in_declaration106);
                if  (HASEXCEPTION())
                {
                    goto ruledeclarationEx;
                }


                if ( LA(1) == 25 || LA(1) == 27 )
                {
                    CONSUME();
                    PERRORRECOVERY=ANTLR3_FALSE;
                }
                else
                {
                    CONSTRUCTEX();
                    EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
                    EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;
                    EXCEPTION->expectingSet = NULL;

                    goto ruledeclarationEx;
                }


            }


            // E:\\Users\\Owen\\Documents\\Work\\Year2\\Laboratory\\MAlice\\malice\\Milestone 2\\MAlice.g:16:49: ( ( 'too' )? )
            // E:\\Users\\Owen\\Documents\\Work\\Year2\\Laboratory\\MAlice\\malice\\Milestone 2\\MAlice.g:16:50: ( 'too' )?
            {
                // E:\\Users\\Owen\\Documents\\Work\\Year2\\Laboratory\\MAlice\\malice\\Milestone 2\\MAlice.g:16:50: ( 'too' )?
                {
                    int alt3=2;
                    switch ( LA(1) )
                    {
                        case 31:
                        	{
                        		alt3=1;
                        	}
                            break;
                    }

                    switch (alt3)
                    {
                	case 1:
                	    // E:\\Users\\Owen\\Documents\\Work\\Year2\\Laboratory\\MAlice\\malice\\Milestone 2\\MAlice.g:16:50: 'too'
                	    {
                	         MATCHT(31, &FOLLOW_31_in_declaration118);
                	        if  (HASEXCEPTION())
                	        {
                	            goto ruledeclarationEx;
                	        }


                	    }
                	    break;

                    }
                }

            }


        }

    }

    // This is where rules clean up and exit
    //
    goto ruledeclarationEx; /* Prevent compiler warnings */
    ruledeclarationEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end declaration */

/**
 * $ANTLR start assignment
 * E:\\Users\\Owen\\Documents\\Work\\Year2\\Laboratory\\MAlice\\malice\\Milestone 2\\MAlice.g:18:1: assignment : ( ID 'became' expression | ID 'became' CHAR );
 */
static void
assignment(pMAliceParser ctx)
{
    /* Initialize rule variables
     */

    {
        {
            //  E:\\Users\\Owen\\Documents\\Work\\Year2\\Laboratory\\MAlice\\malice\\Milestone 2\\MAlice.g:18:11: ( ID 'became' expression | ID 'became' CHAR )

            ANTLR3_UINT32 alt4;

            alt4=2;

            switch ( LA(1) )
            {
            case ID:
            	{
            		switch ( LA(2) )
            		{
            		case 20:
            			{
            				switch ( LA(3) )
            				{
            				case CHAR:
            					{
            						alt4=2;
            					}
            				    break;
            				case ID:
            				case INT:
            				case 34:
            					{
            						alt4=1;
            					}
            				    break;

            				default:
            				    CONSTRUCTEX();
            				    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            				    EXCEPTION->message      = (void *)"";
            				    EXCEPTION->decisionNum  = 4;
            				    EXCEPTION->state        = 2;


            				    goto ruleassignmentEx;

            				}

            			}
            		    break;

            		default:
            		    CONSTRUCTEX();
            		    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            		    EXCEPTION->message      = (void *)"";
            		    EXCEPTION->decisionNum  = 4;
            		    EXCEPTION->state        = 1;


            		    goto ruleassignmentEx;

            		}

            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 4;
                EXCEPTION->state        = 0;


                goto ruleassignmentEx;

            }

            switch (alt4)
            {
        	case 1:
        	    // E:\\Users\\Owen\\Documents\\Work\\Year2\\Laboratory\\MAlice\\malice\\Milestone 2\\MAlice.g:18:13: ID 'became' expression
        	    {
        	         MATCHT(ID, &FOLLOW_ID_in_assignment127);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleassignmentEx;
        	        }


        	         MATCHT(20, &FOLLOW_20_in_assignment129);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleassignmentEx;
        	        }


        	        FOLLOWPUSH(FOLLOW_expression_in_assignment131);
        	        expression(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleassignmentEx;
        	        }


        	    }
        	    break;
        	case 2:
        	    // E:\\Users\\Owen\\Documents\\Work\\Year2\\Laboratory\\MAlice\\malice\\Milestone 2\\MAlice.g:18:38: ID 'became' CHAR
        	    {
        	         MATCHT(ID, &FOLLOW_ID_in_assignment135);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleassignmentEx;
        	        }


        	         MATCHT(20, &FOLLOW_20_in_assignment137);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleassignmentEx;
        	        }


        	         MATCHT(CHAR, &FOLLOW_CHAR_in_assignment139);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleassignmentEx;
        	        }


        	    }
        	    break;

            }
        }
    }

    // This is where rules clean up and exit
    //
    goto ruleassignmentEx; /* Prevent compiler warnings */
    ruleassignmentEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end assignment */

/**
 * $ANTLR start step
 * E:\\Users\\Owen\\Documents\\Work\\Year2\\Laboratory\\MAlice\\malice\\Milestone 2\\MAlice.g:20:1: step : ID ( 'drank' | 'ate' ) ;
 */
static void
step(pMAliceParser ctx)
{
    /* Initialize rule variables
     */

    {
        // E:\\Users\\Owen\\Documents\\Work\\Year2\\Laboratory\\MAlice\\malice\\Milestone 2\\MAlice.g:20:5: ( ID ( 'drank' | 'ate' ) )
        // E:\\Users\\Owen\\Documents\\Work\\Year2\\Laboratory\\MAlice\\malice\\Milestone 2\\MAlice.g:20:8: ID ( 'drank' | 'ate' )
        {
             MATCHT(ID, &FOLLOW_ID_in_step147);
            if  (HASEXCEPTION())
            {
                goto rulestepEx;
            }


            if ( LA(1) == 19 || LA(1) == 23 )
            {
                CONSUME();
                PERRORRECOVERY=ANTLR3_FALSE;
            }
            else
            {
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;
                EXCEPTION->expectingSet = NULL;

                goto rulestepEx;
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto rulestepEx; /* Prevent compiler warnings */
    rulestepEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end step */

/**
 * $ANTLR start expression
 * E:\\Users\\Owen\\Documents\\Work\\Year2\\Laboratory\\MAlice\\malice\\Milestone 2\\MAlice.g:22:1: expression : or ( '^' or )* ;
 */
static void
expression(pMAliceParser ctx)
{
    /* Initialize rule variables
     */

    {
        // E:\\Users\\Owen\\Documents\\Work\\Year2\\Laboratory\\MAlice\\malice\\Milestone 2\\MAlice.g:22:11: ( or ( '^' or )* )
        // E:\\Users\\Owen\\Documents\\Work\\Year2\\Laboratory\\MAlice\\malice\\Milestone 2\\MAlice.g:22:13: or ( '^' or )*
        {
            FOLLOWPUSH(FOLLOW_or_in_expression162);
            or(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleexpressionEx;
            }


            // E:\\Users\\Owen\\Documents\\Work\\Year2\\Laboratory\\MAlice\\malice\\Milestone 2\\MAlice.g:22:16: ( '^' or )*

            for (;;)
            {
                int alt5=2;
                switch ( LA(1) )
                {
                case 17:
                	{
                		alt5=1;
                	}
                    break;

                }

                switch (alt5)
                {
            	case 1:
            	    // E:\\Users\\Owen\\Documents\\Work\\Year2\\Laboratory\\MAlice\\malice\\Milestone 2\\MAlice.g:22:17: '^' or
            	    {
            	         MATCHT(17, &FOLLOW_17_in_expression165);
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleexpressionEx;
            	        }


            	        FOLLOWPUSH(FOLLOW_or_in_expression167);
            	        or(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleexpressionEx;
            	        }


            	    }
            	    break;

            	default:
            	    goto loop5;	/* break out of the loop */
            	    break;
                }
            }
            loop5: ; /* Jump out to here if this rule does not match */


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleexpressionEx; /* Prevent compiler warnings */
    ruleexpressionEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end expression */

/**
 * $ANTLR start or
 * E:\\Users\\Owen\\Documents\\Work\\Year2\\Laboratory\\MAlice\\malice\\Milestone 2\\MAlice.g:24:1: or : and ( '|' and )* ;
 */
static void
or(pMAliceParser ctx)
{
    /* Initialize rule variables
     */

    {
        // E:\\Users\\Owen\\Documents\\Work\\Year2\\Laboratory\\MAlice\\malice\\Milestone 2\\MAlice.g:24:3: ( and ( '|' and )* )
        // E:\\Users\\Owen\\Documents\\Work\\Year2\\Laboratory\\MAlice\\malice\\Milestone 2\\MAlice.g:24:6: and ( '|' and )*
        {
            FOLLOWPUSH(FOLLOW_and_in_or177);
            and(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleorEx;
            }


            // E:\\Users\\Owen\\Documents\\Work\\Year2\\Laboratory\\MAlice\\malice\\Milestone 2\\MAlice.g:24:10: ( '|' and )*

            for (;;)
            {
                int alt6=2;
                switch ( LA(1) )
                {
                case 33:
                	{
                		alt6=1;
                	}
                    break;

                }

                switch (alt6)
                {
            	case 1:
            	    // E:\\Users\\Owen\\Documents\\Work\\Year2\\Laboratory\\MAlice\\malice\\Milestone 2\\MAlice.g:24:11: '|' and
            	    {
            	         MATCHT(33, &FOLLOW_33_in_or180);
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleorEx;
            	        }


            	        FOLLOWPUSH(FOLLOW_and_in_or182);
            	        and(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleorEx;
            	        }


            	    }
            	    break;

            	default:
            	    goto loop6;	/* break out of the loop */
            	    break;
                }
            }
            loop6: ; /* Jump out to here if this rule does not match */


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleorEx; /* Prevent compiler warnings */
    ruleorEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end or */

/**
 * $ANTLR start and
 * E:\\Users\\Owen\\Documents\\Work\\Year2\\Laboratory\\MAlice\\malice\\Milestone 2\\MAlice.g:26:1: and : add ( '&' add )* ;
 */
static void
and(pMAliceParser ctx)
{
    /* Initialize rule variables
     */

    {
        // E:\\Users\\Owen\\Documents\\Work\\Year2\\Laboratory\\MAlice\\malice\\Milestone 2\\MAlice.g:26:4: ( add ( '&' add )* )
        // E:\\Users\\Owen\\Documents\\Work\\Year2\\Laboratory\\MAlice\\malice\\Milestone 2\\MAlice.g:26:7: add ( '&' add )*
        {
            FOLLOWPUSH(FOLLOW_add_in_and193);
            add(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleandEx;
            }


            // E:\\Users\\Owen\\Documents\\Work\\Year2\\Laboratory\\MAlice\\malice\\Milestone 2\\MAlice.g:26:11: ( '&' add )*

            for (;;)
            {
                int alt7=2;
                switch ( LA(1) )
                {
                case 8:
                	{
                		alt7=1;
                	}
                    break;

                }

                switch (alt7)
                {
            	case 1:
            	    // E:\\Users\\Owen\\Documents\\Work\\Year2\\Laboratory\\MAlice\\malice\\Milestone 2\\MAlice.g:26:12: '&' add
            	    {
            	         MATCHT(8, &FOLLOW_8_in_and196);
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleandEx;
            	        }


            	        FOLLOWPUSH(FOLLOW_add_in_and198);
            	        add(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleandEx;
            	        }


            	    }
            	    break;

            	default:
            	    goto loop7;	/* break out of the loop */
            	    break;
                }
            }
            loop7: ; /* Jump out to here if this rule does not match */


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleandEx; /* Prevent compiler warnings */
    ruleandEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end and */

/**
 * $ANTLR start add
 * E:\\Users\\Owen\\Documents\\Work\\Year2\\Laboratory\\MAlice\\malice\\Milestone 2\\MAlice.g:28:1: add : ones ( '+' ones )* ;
 */
static void
add(pMAliceParser ctx)
{
    /* Initialize rule variables
     */

    {
        // E:\\Users\\Owen\\Documents\\Work\\Year2\\Laboratory\\MAlice\\malice\\Milestone 2\\MAlice.g:28:4: ( ones ( '+' ones )* )
        // E:\\Users\\Owen\\Documents\\Work\\Year2\\Laboratory\\MAlice\\malice\\Milestone 2\\MAlice.g:28:7: ones ( '+' ones )*
        {
            FOLLOWPUSH(FOLLOW_ones_in_add208);
            ones(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleaddEx;
            }


            // E:\\Users\\Owen\\Documents\\Work\\Year2\\Laboratory\\MAlice\\malice\\Milestone 2\\MAlice.g:28:12: ( '+' ones )*

            for (;;)
            {
                int alt8=2;
                switch ( LA(1) )
                {
                case 11:
                	{
                		alt8=1;
                	}
                    break;

                }

                switch (alt8)
                {
            	case 1:
            	    // E:\\Users\\Owen\\Documents\\Work\\Year2\\Laboratory\\MAlice\\malice\\Milestone 2\\MAlice.g:28:13: '+' ones
            	    {
            	         MATCHT(11, &FOLLOW_11_in_add211);
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleaddEx;
            	        }


            	        FOLLOWPUSH(FOLLOW_ones_in_add213);
            	        ones(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleaddEx;
            	        }


            	    }
            	    break;

            	default:
            	    goto loop8;	/* break out of the loop */
            	    break;
                }
            }
            loop8: ; /* Jump out to here if this rule does not match */


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleaddEx; /* Prevent compiler warnings */
    ruleaddEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end add */

/**
 * $ANTLR start ones
 * E:\\Users\\Owen\\Documents\\Work\\Year2\\Laboratory\\MAlice\\malice\\Milestone 2\\MAlice.g:30:1: ones : term ( ( '/' | '*' | '%' ) term )* ;
 */
static void
ones(pMAliceParser ctx)
{
    /* Initialize rule variables
     */

    {
        // E:\\Users\\Owen\\Documents\\Work\\Year2\\Laboratory\\MAlice\\malice\\Milestone 2\\MAlice.g:30:5: ( term ( ( '/' | '*' | '%' ) term )* )
        // E:\\Users\\Owen\\Documents\\Work\\Year2\\Laboratory\\MAlice\\malice\\Milestone 2\\MAlice.g:30:8: term ( ( '/' | '*' | '%' ) term )*
        {
            FOLLOWPUSH(FOLLOW_term_in_ones223);
            term(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleonesEx;
            }


            // E:\\Users\\Owen\\Documents\\Work\\Year2\\Laboratory\\MAlice\\malice\\Milestone 2\\MAlice.g:30:13: ( ( '/' | '*' | '%' ) term )*

            for (;;)
            {
                int alt9=2;
                switch ( LA(1) )
                {
                case 7:
                case 10:
                case 14:
                	{
                		alt9=1;
                	}
                    break;

                }

                switch (alt9)
                {
            	case 1:
            	    // E:\\Users\\Owen\\Documents\\Work\\Year2\\Laboratory\\MAlice\\malice\\Milestone 2\\MAlice.g:30:14: ( '/' | '*' | '%' ) term
            	    {
            	        if ( LA(1) == 7 || LA(1) == 10 || LA(1) == 14 )
            	        {
            	            CONSUME();
            	            PERRORRECOVERY=ANTLR3_FALSE;
            	        }
            	        else
            	        {
            	            CONSTRUCTEX();
            	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
            	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;
            	            EXCEPTION->expectingSet = NULL;

            	            goto ruleonesEx;
            	        }


            	        FOLLOWPUSH(FOLLOW_term_in_ones238);
            	        term(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleonesEx;
            	        }


            	    }
            	    break;

            	default:
            	    goto loop9;	/* break out of the loop */
            	    break;
                }
            }
            loop9: ; /* Jump out to here if this rule does not match */


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleonesEx; /* Prevent compiler warnings */
    ruleonesEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end ones */

/**
 * $ANTLR start term
 * E:\\Users\\Owen\\Documents\\Work\\Year2\\Laboratory\\MAlice\\malice\\Milestone 2\\MAlice.g:32:1: term : ( ( '~' term ) | ID | INT );
 */
static void
term(pMAliceParser ctx)
{
    /* Initialize rule variables
     */

    {
        {
            //  E:\\Users\\Owen\\Documents\\Work\\Year2\\Laboratory\\MAlice\\malice\\Milestone 2\\MAlice.g:32:5: ( ( '~' term ) | ID | INT )

            ANTLR3_UINT32 alt10;

            alt10=3;

            switch ( LA(1) )
            {
            case 34:
            	{
            		alt10=1;
            	}
                break;
            case ID:
            	{
            		alt10=2;
            	}
                break;
            case INT:
            	{
            		alt10=3;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 10;
                EXCEPTION->state        = 0;


                goto ruletermEx;

            }

            switch (alt10)
            {
        	case 1:
        	    // E:\\Users\\Owen\\Documents\\Work\\Year2\\Laboratory\\MAlice\\malice\\Milestone 2\\MAlice.g:32:8: ( '~' term )
        	    {
        	        // E:\\Users\\Owen\\Documents\\Work\\Year2\\Laboratory\\MAlice\\malice\\Milestone 2\\MAlice.g:32:8: ( '~' term )
        	        // E:\\Users\\Owen\\Documents\\Work\\Year2\\Laboratory\\MAlice\\malice\\Milestone 2\\MAlice.g:32:9: '~' term
        	        {
        	             MATCHT(34, &FOLLOW_34_in_term249);
        	            if  (HASEXCEPTION())
        	            {
        	                goto ruletermEx;
        	            }


        	            FOLLOWPUSH(FOLLOW_term_in_term251);
        	            term(ctx);

        	            FOLLOWPOP();
        	            if  (HASEXCEPTION())
        	            {
        	                goto ruletermEx;
        	            }


        	        }


        	    }
        	    break;
        	case 2:
        	    // E:\\Users\\Owen\\Documents\\Work\\Year2\\Laboratory\\MAlice\\malice\\Milestone 2\\MAlice.g:32:21: ID
        	    {
        	         MATCHT(ID, &FOLLOW_ID_in_term256);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruletermEx;
        	        }


        	    }
        	    break;
        	case 3:
        	    // E:\\Users\\Owen\\Documents\\Work\\Year2\\Laboratory\\MAlice\\malice\\Milestone 2\\MAlice.g:32:26: INT
        	    {
        	         MATCHT(INT, &FOLLOW_INT_in_term260);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruletermEx;
        	        }


        	    }
        	    break;

            }
        }
    }

    // This is where rules clean up and exit
    //
    goto ruletermEx; /* Prevent compiler warnings */
    ruletermEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end term */
/* End of parsing rules
 * ==============================================
 */

/* ==============================================
 * Syntactic predicates
 */
/* End of syntactic predicates
 * ==============================================
 */






/* End of code
 * =============================================================================
 */
